### ISSUE TITLE
Useless Backend Notification

### ISSUE THREAD

**Issue by mschnye** [pfpayments/woocommerce#25]
Hi,
In the WP Backend is permanently displayed "A version of the PostFinanceCheckout plugin is yet to be released for this version of WooCommerce."

Please remove this. It's pointless 

Thank you.
Marco

**Comment by KuhnDaniel** [comment]
the same with the latest versions wp and pfpayments woocommerce today 08/13/2023 
updated everything and still the message

Best regards
Daniel

**Comment by thibault-mambour** [comment]
hi @mschnye , the latest release should fix the problem. Could you please confirm ?

**Comment by mschnye** [comment]
Hi,We have the latest released version 2.1.28 installed and it’s still visible.Freundliche Grüsse Marco SchnyderVom Phone gesendetAm 25.02.2024 um 22:03 schrieb thibault-mambour ***@***.***>:﻿
hi @mschnye , the latest release should fix the problem. Could you please confirm ?

**Comment by thibault-mambour** [comment]
Hi @mschnye , the latest released version is 3.0.0. It should be fixed on that version

**Comment by mschnye** [comment]
On Wordpress the next possible version is 3.0.0-rc1. We do not install release candidates.

 

Von: thibault-mambour ***@***.***> 
Gesendet: Dienstag, 5. März 2024 16:30
An: pfpayments/woocommerce ***@***.***>
Cc: mschnye ***@***.***>; Mention ***@***.***>
Betreff: Re: [pfpayments/woocommerce] Useless Backend Notification (Issue #25)

 

Hi @mschnye <https://github.com/mschnye>  , the latest released version is 3.0.0. It should be fixed on that version

**Comment by mschnye** [comment]
Hi, this is still not fixed, even in 3.0.4.

![postfinance checkout backend text](https://github.com/pfpayments/woocommerce/assets/28760372/4c96475a-b6f5-4a5f-96ff-4a66a5dee2dd)
